#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.

def solve(a, b):
    p1=0;
    p2=0;
    for i in range(3):
        if(a[i]>b[i]):
            p1=p1+1
        elif(a[i]<b[i]):
            p2=p2+1
    return "%d%d" % (p1,p2)
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = solve(a, b)
    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
