#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the diagonalDifference function below.
def diagonalDifference(arr):
    n=0
    sum1=0
    sum2=0
    for i in range(len(arr[0])):
        n=n+1
    for i in range(n):
        sum1=sum1+arr[i][i]
        
        sum2=sum2+arr[i][n-1-i]
        
    return sum2-sum1
    
        
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
